version: '3'
services:
  app:
    container_name: base-project
    restart: always
    build: .
    ports:
      - '5001:5000'
    links:
      - mongo
    volumes:
      - .:/src
  mongo:
    container_name: mongo
    image: mongo:5.0.0
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
